# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-01 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table='my_owner_table',
        ),
    ]
